### ISSUE TITLE
Week of February 20th 2015

### ISSUE THREAD

**Issue by tianp** [iojs/iojs-id#10]
https://medium.com/node-js-javascript/io-js-week-of-february-20th-2015-48486615980

Yak siapa yang mau ngambil silakan comment dibawah ya, supaya gak ada beberapa orang ngerjain tugas yang sama.

**Comment by herpiko** [comment]
Saya coba.

**Comment by tianp** [comment]
gmn updatenya mas @herpiko?

**Comment by herpiko** [comment]
sedikit lagi pak @tianp, tinggal menambahkan pranala

**Comment by herpiko** [comment]
Maaf, ini sangat terlambat. Mohon di-review. #12

**Comment by tianp** [comment]
Sip, thank mas @herpiko sudah di-merge ya.
