### ISSUE TITLE
Translasi Roadmap

### ISSUE THREAD

**Issue by tianp** [iojs/iojs-id#11]
Let's working on this: https://github.com/iojs/roadmap/issues/18

**Comment by herpiko** [comment]
Ada yang sudah pegang tugas ini?

**Comment by diagramatics** [comment]
Mungkin kalau tugasnya terlalu banyak bisa kita pecah agar satu orang menerjemahkan satu slide?

**Comment by junwatu** [comment]
@diagramatics  ide yang bagus.

**Comment by diagramatics** [comment]
Nggak bisa tidur, jadi seharian terjemah doang. Mohon bantuannya cek iojs/roadmap#43 apabila ada yang salah atau ada jargon yang lebih baik diterjemah atau dipertahankan dalam Bahasa Inggris.

Ping @aredo juga, in case JakartaJS sudah siap menerima io.js :)

**Comment by yaditya** [comment]
Interested to help with the translation. Ada yang berkenan share informasi tentang how to start? Thanks heaps! PS: Saya sudah sempat tinggalkan beberapa komen di pull request roadmap#43 milik diagramatics

**Comment by hengkiardo** [comment]
@diagramatics kita dari JakartaJS sih kalau mau ada event yg related JS pasti bantu.

tapi kebetulan organizer kita jg lagi sibuk bgt.. jadi kurang aktif.

**Comment by diagramatics** [comment]
Halo mas @yaditya, senang bisa berjumpa disini! Kebetulan biasanya kami melacak adanya perubahan atau tidak di sekitar io.js yang perlu diterjemahkan, tetapi setiap hari Jumat (Sabtu kalau Indonesia dan Australia) selalu ada _weekly update_ [di Medium](https://medium.com/@iojs) yang perlu kita terjemahkan dan biasanya saya selalu buka issue di GitHub untuk memberikan kesempatan komunitas kita untuk menerjemahkannya. Selain dari itu, belum ada yang terlalu menantang :)

@aredo Kalau gitu boleh dong dicek terjemahan roadmapnya apakah sudah mantap atau belum untuk dibawa ke acara-acara seperti ini :)

**Comment by tianp** [comment]
Halo @yaditya salam kenal! Dan baru sadar ada mas @junwatu dari @idjs, selamat datang mas :D

**Comment by hengkiardo** [comment]
umumnya si kalo ke acara meetup slide itu gak harus bahasa indonesia ya, karena di beberapa kesempatan kita ada jg tamu yg datang bukan orang indonesia, dan so far kalo yg jd speaker di meetup jakartajs kebanyakan slide mereka dengan english.

**Comment by diagramatics** [comment]
iojs/roadmap#43 sudah dimerge. Terima kasih bantuannya :+1:
