### ISSUE TITLE
[Terjemah] io.js Week of February 27th

### ISSUE THREAD

**Issue by diagramatics** [iojs/iojs-id#13]
Pos ada disini: https://medium.com/node-js-javascript/io-js-week-of-february-17th-9422a589302a

Jika tidak ada yang mengajukan diri ada kemungkinan saya akan menerjemahkan yang satu ini. Kebetulan sedang liburan dan tidak bisa berbuat banyak.

**Comment by tianp** [comment]
wah udah post baru lagi ya, silakan bro @diagramatics :+1:

**Comment by diagramatics** [comment]
Pos barunya selalu akan muncul setiap hari Jumat, btw. Saya akan mengambil alih yang satu ini.

**Comment by diagramatics** [comment]
Hasil terjemahan ada di #14. Harap dicek terlebih dahulu sebelum di-merge.

**Comment by tianp** [comment]
Minor typo, sudah saya tambahkan di PR, tapi overall sudah ok.
