### ISSUE TITLE
[website] Ganti index.md menjadi sistem template berbasis template.json

### ISSUE THREAD

**Issue by diagramatics** [iojs/iojs-id#19]
Build system di iojs/website sedang diganti, dan index.md disarankan dibuang agar kontennya dimuat saat build dari value di template.json. Detailnya ada di iojs/website#276.

Saya sudah sempat membuat PR di iojs/website#304, jadi mohon bantuannya untuk pengecekan dan lainnya.

**Comment by diagramatics** [comment]
Ada tambahan terjemahan di halaman "Releases", terjemahan ada di iojs/website#310. Mohon bantuannya.

**Comment by diagramatics** [comment]
Semua update terbaru sudah diupdate ke repo kita via commit e8c9b6c91e489f261d6dae11da1a9cf0c98e2e48.

**Comment by tianp** [comment]
Cool job @diagramatics !
