### ISSUE TITLE
My draft of the latest io.js post

### ISSUE THREAD

**Issue by diagramatics** [iojs/iojs-id#2]
I wrote this in Markdown for the simplicity of pasting it to GitHub. There are some words that I'm not sure of if it sets the same tone as the English counterpart—formal or informal tone and/or whatnot. I also rewrote some sentences that sound weird when immediately translated to Indonesian, and left some group words in English because I can't find the counterpart in Indonesian.

Also I have no idea of where should we put this on. Medium is fairly unknown by Indonesians yet there isn't any good writing platforms & communities out there that is common for Indonesians. I guess Medium should be fine.

P.S:
Ini masih draft kasar. Saya bukan penerjemah yang baik jadi bakal ada terjemahan yang bahasanya nggak _ngeh_ kalau dibaca pakai Bahasa Indonesia, belum lagi bahasa teknis yang terjemahannya kurang dipahami oleh orang Indonesia juga. Mohon dicek dahulu dan salam kenal.

---

io.js Mingguan, 6 Februari 2015
Atom & nw.js mengadopsi io.js, Linux Tracing, dan masih banyak lagi.

Setiap hari Jumat kami akan mulai memberikan update mingguan mengenai aktivitas di dalam dan disekitar io.js.

Kami mengingat kembali pada semua kontribusi dalam bulan Januari dan menemukan bahwa bulan tersebut adalah **bulan ke-3 paling aktif dalam sejarah Node (294 commit)** dan bulan paling aktif dalam hampir **tiga tahun (308 commit dalam Februari 2012)**. Dengan pertumbuhan kontribusi yang kami lihat selama ini kami berharap Februari akan lebih aktif lagi.
1. [**1.1.0**](https://iojs.org/dist/v1.1.0/) telah dirilis, ceklah [**Changelog**](https://github.com/iojs/io.js/blob/v1.x/CHANGELOG.md#2015-02-03-version-110-chrisdickinson) tersebut.
2. [**Simplified Stream Construction**](https://github.com/iojs/io.js/commit/50daee7243a3f987e1a28d93c43f913471d6885a) oleh Sam Newman mendarat.
3. **Linux Tracing** (LTTNG) [sedang ditambahkan](https://github.com/iojs/io.js/pull/702).
4. Google [membagikan beberapa dari **hasil kerja tracing**](https://github.com/iojs/io.js/issues/671#issuecomment-73191538) **dalam v8 dan Chrome** selagi kami memperketat kolaborasi disekitar upaya debugging io.js.
5. [Dukungan io.js ditambahkan pada **Travis CI**](http://docs.travis-ci.com/user/build-environment-updates/2015-02-03/).
6. [**Codeship** mendukung io.js](https://codeship.com/documentation/languages/nodejs/#iojs).
7. [**Atom Editor** pindah ke io.js](https://github.com/atom/atom/releases/tag/v0.177.0).
8. **nw.js** (dulunya bernama **node-webkit**) [pindah ke io.js](https://github.com/nwjs/nw.js/issues/2742).
9. Perangkat keras **Tessel** yang baru [akan mendukung io.js](http://blog.technical.io/post/110115579867/upcoming-hardware-from-technical-machine).
10. Chris Dickinson menambahkan [**enam committer baru**](https://github.com/iojs/io.js/issues/680#issuecomment-73089691), membuat angka **total committer aktif menjadi 23**.
11. Sedang mengerjakan [**Kebijaksanaan Stabilitas dan Kompatibilitas**](https://github.com/iojs/io.js/issues/725), kami sangat mendorong partisipasi dari komunitas.
12. Kami telah memulai berhubungan dengan [perusahaan untuk meminta feedback](https://github.com/iojs/roadmap/issues/13) mengenai **roadmap** kami. Jika anda mempunyai kontak perusahaan yang kami lupa tolong beritahu kami.
13. Minggu depan adalah [**Node Summit**](http://nodesummit.com/) dengan banyak sekali orang-orang io.js berbicara dan menghadiri acara tersebut.
14. [Pertemuan Mingguan TC](https://www.youtube.com/watch?v=IhXa2FmtBI4).
15. [Pertemuan Website Working Group](https://www.youtube.com/watch?v=SBJaXUA0lSY).
16. [Pertemuan Tracing Working Group](https://www.youtube.com/watch?v=Oar2yB5SPtA).

**Comment by tianp** [comment]
Hi @diagramatics, your translation is quite good. I made a [PR](https://github.com/iojs/iojs-id/pull/3) based on this translation with minor changes.

@diorahman please kindly review the PR, thanks.

**Comment by diagramatics** [comment]
Not sure if we should use PRs for this since we only need to translate it and post to a writing platform of our choice, or at least that's what #1 says. I can always edit my original post with the new changes.

**Comment by tianp** [comment]
@diagramatics yes, that was also my question until I checked other localization repos. Some of them are pushing the weekly translation into their repo, not sure why but IMO would be nice if we have a good archive of them, don't you think?

**Comment by diagramatics** [comment]
Well, we can just archive it in the writing platform of our choice, so it feels kind of pointless IMO. Plus we're not really sure that the writing platform will have Markdown support—Medium doesn't as far as I know.

**Comment by tianp** [comment]
@diagramatics that's sounds a good reason, but I'm not sure why are you concerning about formatting support. Anyway, let's move on to writing platform, do we need to create new issue regarding this?

**Comment by diagramatics** [comment]
Small concerns, really. I was thinking that having the archive is useless since if we post it on Medium or WordPress we can't really copy the WYSIWYG output and dump it into GitHub. Unless we use Svbtle, Jekyll or any other places that support Markdown having an archive in GitHub is pretty much useless.

And not to be very salty or very self-entitled about this, but I was going to suggest me opening the PR if we do archive it, since I was doing the initial translation (just trying to archive open-source contributions to fill the somewhat-lacking portfolio). But since @diorahman had merged the PR without any discussion or feedback whatsoever, I guess I had no other options but to comply.

Ah, and sure, create a new issue about that, I suppose. Or we can continue discussions here. Your call.

**Comment by diorahman** [comment]
I prefer to use PR-based contribution. Well, I also prefer if we just use **Bahasa Indonesia** in this repository. 

I have invited you two as collaborators. Feel free to do direct commit against this repo when you think it is make sense. When you need comments, please submit the proposal as PR.

The hard work, I guess is to translate the iojs docs. As what is done by _.no_ folks on http://www.iojs.no/. I'll try to setup a suitable place for that, meanwhile we can just use the `gh_pages` branch to do that.

I'm closing this issue. (If you feel it is not right, you can always **buka tiket ini kembali**)

Terimakasih.
