### ISSUE TITLE
Penambahan Daftar Kontributor

### ISSUE THREAD

**Issue by tianp** [iojs/iojs-id#27]
Guys, baru saja saya menambahkan daftar kontributor di file README, informasi kontributor saya tambahkan berdasarkan kontribusi yang dilakukan untuk penerjemahan io.js Bahasa Indonesia baik publikasi di [Medium](https://medium.com/@iojs_id) dan yang lainnya seperti [Roadmap](http://roadmap.iojs.org/id/) dan [Website](https://iojs.org/id). 

Saya sudah menambahkan @aredo dan @yaditya sebagai kontributor, mohon tambahkan yang lain jika ada yang terlewat.

**Comment by diagramatics** [comment]
+1, sepertinya nggak ada lagi yang terlewat. Kebetulan saya juga tidak punya _permission_ untuk menambahkan orang ke org iojs atau ke tim iojs-id. Mas @tianp atau @diorahman ada?

**Comment by tianp** [comment]
Ditutup ya.
