### ISSUE TITLE
Kehilangan hak admin

### ISSUE THREAD

**Issue by herpiko** [iojs/iojs-id#28]
Halo,

Saya kurang yakin tetapi saya dan seorang lagi (@tuanpembual) tidak dapat mengakses laman settings. Apakah ada yang mengalami hal yang sama? Jika ada yang masih di dalam group admin, apakah bisa meng-invite ulang?

**Comment by tuanpembual** [comment]
saya ingin mengkorfimasi masalah ini, barangkali saya salah pencet. Apakah ada owner yang bisa mengecek ulang tim member iojs-id?

**Comment by diagramatics** [comment]
Wah, kok begini. Seluruh tim iojs-id kehilangan akses admin ke repo ini, cuman write doang. Perlu saya paging ke atasan dulu nih?

**Comment by herpiko** [comment]
Perlu, pak.

**Comment by diagramatics** [comment]
Hi @mikeal, the iojs-id seems to have lost the admin privileges on this repo, which I think has been the case for quite some time. Is this intended?

**Comment by mikeal** [comment]
Fixed :)

**Comment by diagramatics** [comment]
Thanks! :)
