### ISSUE TITLE
how to join to this team

### ISSUE THREAD

**Issue by hengkiardo** [iojs/iojs-id#4]
what the task list to do if join to this team localization? let me know, maybe i can helping something
@diagramatics @diorahman @tianp ??

cheers.

**Comment by diagramatics** [comment]
Halo halo! Biar gampang pakai Bahasa Indonesia saja. 

Kami belum punya task list yang konkrit, soalnya sepertinya semua anggota tim sedang sibuk. Setelah kami susun kami akan membuka banyak issue untuk meminta pertolongan menerjemahkan bagian-bagian tertentu, atau mungkin Mas punya ide apa yang harus diterjemahkan dahulu juga bisa diusulkan :)

**Comment by tianp** [comment]
Hi @aredo, ini Hengki dari JakartaJS ya? 

@diagramatics btw, saya sudah membuat issue perihal translasi web #5 . I think it can be the start.

**Comment by hengkiardo** [comment]
@tianp personally saya bukan dari JakartaJS, tapi mungkin team jakartajs jg bisa colaboration untuk bantu.

**Comment by diagramatics** [comment]
Hasil kontribusi sudah menunjukkan niat. Saya sih oke-oke saja, tapi sepertinya mas @diorahman yang bisa invite masuk ke tim.

**Comment by tianp** [comment]
Sepertinya beberapa hari yang lalu saya bisa mencoba invite user ke dalam team `iojs-id`, tapi baru saja dicoba sudah tidak bisa lagi. Saat ini saya hanya bisa menambahkan collaborator repository, is that okay? @aredo

**Comment by tianp** [comment]
Sudah saya tambahkan ke collaborator ya @aredo :)
