### ISSUE TITLE
[Terjemah] io.js Week of 29th May

### ISSUE THREAD

**Issue by diagramatics** [iojs/iojs-id#40]
Ping tim @nodejs/iojs-id kalau ada yang berminat.

**Comment by tianp** [comment]
Sorry absen minggu kemarin, ini saya ambil ya.

**Comment by diagramatics** [comment]
Hajar aja mas, ada di nodejs/evangelism#89.

**Comment by tianp** [comment]
Sudah ada di PR https://github.com/nodejs/iojs-id/pull/41 ya

**Comment by diagramatics** [comment]
Publikasi ada di [sini](https://medium.com/@iojs_id/io-js-pekan-29-mei-2379e42e4ed7).
