### ISSUE TITLE
Translasi Web

### ISSUE THREAD

**Issue by tianp** [iojs/iojs-id#5]
Guys, sepertinya kita sudah harus memulai translasi web. Apa kita bisa mulai dengan Github Pages seperti tim Norwegia https://github.com/iojs-no? 

Apakah ada ide untuk pendekatan lain?

**Comment by hengkiardo** [comment]
untuk bikin organization baru kyk nya masih di perbincangkan disini https://github.com/iojs/website/issues/136

**Comment by tianp** [comment]
@aredo barusan baca, memang jadi sedikit membingungkan ya.

Ada ide untuk memulai ini? cc @diagramatics @diorahman 

Apakah kita perlu..
1. Membuat branch khusus untuk translasi `website`, atau
2. Menambahkan direktori `/website/content/id` di branch master
3. ...?

**Comment by tianp** [comment]
Heads up, 

Melihat dari tim `iojs/iojs-es` yang membuat direktori `content` pada repository mereka untuk mengerjakan translasi web dan ternyata juga sudah di merge ke `iojs/website`. Maka kita bisa mulai saja dengan pendekatan seperti itu ya. 

Saya akan menambahkan direktori `content/id` di branch master yang berisi file-file yang di-copy dari https://github.com/iojs/website/tree/master/content/id , dan kita bisa mulai translasi web dari file-file tsb.

**Comment by hengkiardo** [comment]
@tianp saya sudah melakukan pull request ke [iojs/website](https://github.com/iojs/website)

berikut ini pull request https://github.com/iojs/website/pull/207

kalau ada yg mau bantu revisi, silakan.

**Comment by herpiko** [comment]
Apakah perlu dibuat ruang diskusi tersendiri (misal issue terpisah) mengenai keputusan tentang kata-kata tertentu? Karena perlu dibuat kesepakatan-kesepakatan mengenai hal itu. Misal seperti open governance, mau diterjemahkan seperti apa. Untuk menghindari satu penerjemah tetap pakai _open governance_, yang lain pakai pemerintahan terbuka. Jadi output akhirnya, daftar kata terjemahan (bukan kata umum) yang menjadi standar dalam tim ini.

**Comment by diagramatics** [comment]
Barusan ngecek hasil kerja @aredo dan @herpiko, mantap.

Ide @herpiko juga bagus. Apakah lebih bagus membuat sebuah issue besar untuk mendokumentasikan jargon-jargon tersebut atau membuat sebuah file Markdown berisi daftar kata-kata yang sudah disepakati menjadi terjemahannya?

**Comment by tianp** [comment]
Saya lihat PR dari @aredo sudah di-merge di repo `iojs/website` ya, apa perlu di-sinkron-kan ke repository kita? For next collaboration? Ada pendapat?

**Comment by tuanpembual** [comment]
saya usul disinkronisasikan saja, karena saya lihat masih ada sedikit typo,
ada pendapat lain?

**Comment by tianp** [comment]
allright, bro @aredo bisa minta tolong buatkan PR ke repository kita sesuai dengan versi yang sudah di-merge?

**Comment by hengkiardo** [comment]
Hi all,
sudah saya push ya.

ini hanya pendapat saya, kalau misal kita edit files `content/id/` dan kemudian PR ke [iojs/website](https://github.com/iojs/website) sepertinya agak sulit karena structure file yg ada di repo ini dengan di `iojs/website` itu sangat berbeda.

**Comment by tianp** [comment]
Thanks @aredo, btw bener juga ya gimana caranya tim `iojs/iojs-es` melakukan PR ke `iojs/website` karena mereka pun menggunakan direktori seperti itu.

**Comment by tianp** [comment]
Closed ya, jika dibutuhkan silakan buka kembali.
