### ISSUE TITLE
Ingin bergabung

### ISSUE THREAD

**Issue by herpiko** [iojs/iojs-id#6]
Hi,
Saya senang sekali jika diizinkan bergabung dan diberi daftar tugas.

**Comment by diagramatics** [comment]
Mas @diorahman sepertinya sudah menginvite sebelum saya masuk ke tim, jadi selamat bergabung. Tugas masih belum ada, tetapi mas @tianp sepertinya sedang meninjau tugas apa yang perlu kita lakukan.

**Comment by tianp** [comment]
Hi, selamat bergabung mas @herpiko :)
