### ISSUE TITLE
Sosial media dan media publikasi iojs-id

### ISSUE THREAD

**Issue by diagramatics** [iojs/iojs-id#7]
Sementara ini yang kita punya hanyalah [Twitter](http://twitter.com/iojs_id). Kita masih perlu beberapa akun sosial media alternatif untuk menyelesaikan tugas awal yang diberikan saat pembentukan repo ini (#1). Kita juga perlu menyebarkan informasi adanya tim kita di komunitas-komunitas JS di Indonesia juga, via retweet atau sebuah shoutout saat gathering mereka yang selanjutnya.

Media publikasi juga perlu dipertimbangkan. Indonesia tidak punya media publikasi yang populer jadi kita punya pilihan yang luas, antara WordPress, Blogger, atau Medium (atau Svbtle kalau kita memilih mempos semua terjemahan pos iojs Medium menjadi Markdown). Saya sendiri lebih memilih Medium.

**Comment by tianp** [comment]
Bro @diagramatics sampai sekarang saya juga masih bingung mau pakai media publikasi apa. Kita vote aja gimana?

**Comment by diagramatics** [comment]
Boleh voting. Saya duluan vote Medium deh karena kita nggak perlu setup design dan domain segala, plus Medium sudah ada komunitas untuk membantu mempublikasikan hasil terjemahan kita ke publik.

**Comment by tuanpembual** [comment]
saya akur pake medium :)

**Comment by diagramatics** [comment]
Jika tidak ada yang mengusulkan hal yang lain di tim @iojs/iojs-id, setelah Mas @herpiko selesai dengan terjemahannya saya akan membuat akun Medium dan menaruh konten kita disana.

**Comment by tianp** [comment]
sip bro @diagramatics, langsung publish saja content yang ada di directori `publications` :+1:
