### ISSUE TITLE
[Terjemah] io.js Week of February 13th 2015

### ISSUE THREAD

**Issue by diagramatics** [iojs/iojs-id#8]
[Pos ada disini](https://medium.com/node-js-javascript/io-js-week-of-february-13th-2015-7846b94074a2). Kita akan perlu menerjemahkan pos-pos baru yang muncul di akun io.js di Medium, dan sepertinya dalam waktu dekat akan ada pos baru juga.

Terjemahan biasanya dilakukan di Markdown untuk dokumentasi dan pengarsipan yang lebih gampang, tetapi ini mungkin berubah ketika kita memutuskan untuk memilih media publikasi yang tidak mendukung Markdown. Untuk sementara, Markdown saja.

**Comment by tianp** [comment]
bro @diagramatics, Week Feb 13th sudah dipush oleh saya beberapa hari yang lalu.

**Comment by diagramatics** [comment]
Eh, astaga! Maaf, maaf. Kalau begitu saya close, kerja yang mantap.
